services:
  roscore:
    image: system_base:ros_noetic_source
    command: /bin/bash -c "source /opt/ros/noetic/setup.bash && roscore"
    network_mode: host

  rviz:
    image: system_base:ros_noetic_source
    command: /bin/bash -c "source /opt/ros/noetic/setup.bash && rviz"
    depends_on:
      - roscore
    runtime: nvidia
    environment:
      - DISPLAY=${DISPLAY}
      - "ROS_MASTER_URI=http://localhost:11311"
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=all
      - QT_X11_NO_MITSHM=1
    volumes:
      - ${HOME}/.Xauthority:/root/.Xauthority:rw
      - /tmp/.X11-unix:/tmp/.X11-unix
      - /etc/group:/etc/group:ro
      - /etc/passwd:/etc/passwd:ro
      - /etc/shadow:/etc/shadow:ro
      - /etc/sudoers:/etc/sudoers:ro
      - /etc/sudoers.d:/etc/sudoers.d:ro
      - /home/${USER}:/home/${USER}:rw #share your home with write permissions
    network_mode: host
  
  # rosbash:
  #   image: system_base:ros_noetic_source
  #   container_name: rosbash
  #   command: bash
  #   depends_on:
  #     - roscore
  #   network_mode: host
  #   environment:
  #     - "ROS_MASTER_URI=http://localhost:11311"
  #   stdin_open: true
  #   tty: true

  ouster_lidar:
    image: ubuntu20-ros-noetic:ouster
    command: /bin/bash -c "while true; do sleep 1000; done"
    depends_on:
      - roscore
    environment:
      - "ROS_MASTER_URI=http://localhost:11311"
    volumes:
      - /home/cerlab/ros_noetic_docker_home/ouster_ws:/ouster_ws:rw
    network_mode: host
    extra_hosts:
      - "os-122412000058.local:169.254.185.8"  # IPv4 address of the Lidar: This is necessary for ping the ouster hostname