services:
  roscore:
    image: system_base:ros_noetic_source
    command: roscore
    network_mode: host

  rviz:
    image: system_base:ros_noetic_source
    command: rviz
    depends_on:
      - roscore
    runtime: nvidia
    environment:
      - DISPLAY=${DISPLAY}
      - "ROS_MASTER_URI=http://localhost:11311"
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=all
      - QT_X11_NO_MITSHM=1
    user: ${UID}
    volumes:
      - ${HOME}/.Xauthority:/root/.Xauthority:rw
      - /tmp/.X11-unix:/tmp/.X11-unix
      - /etc/group:/etc/group:ro
      - /etc/passwd:/etc/passwd:ro
      - /etc/shadow:/etc/shadow:ro
      - /etc/sudoers:/etc/sudoers:ro
      - /etc/sudoers.d:/etc/sudoers.d:ro
      - /home/${USER}:/home/${USER}:rw #share your home with write permissions
    network_mode: host

  # rosbash:
  #   image: system_base:ros_noetic_source
  #   container_name: rosbash
  #   command: bash
  #   stdin_open: true
  #   tty: true
  #   depends_on:
  #     - roscore
  #   environment: